const fallback=[
 ['بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ','Au nom d’Allah, le Tout Miséricordieux, le Très Miséricordieux.','In the Name of Allah—the Most Compassionate, Most Merciful.'],
 ['الم','Alif, Lâm, Mîm.','Alif-Lãm-Mĩm.'],
 ['ذَٰلِكَ الْكِتَابُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِّلْمُتَّقِينَ','C’est le Livre au sujet duquel il n’y a aucun doute, c’est un guide pour les pieux.','This is the Book! There is no doubt about it—a guide for those mindful of Allah.'],
 ['الَّذِينَ يُؤْمِنُونَ بِالْغَيْبِ وَيُقِيمُونَ الصَّلَاةَ وَمِمَّا رَزَقْنَاهُمْ يُنفِقُونَ','qui croient à l’invisible, accomplissent la prière et dépensent de ce que Nous leur avons attribué,','who believe in the unseen, establish prayer, and donate from what We have provided for them,'],
 ['وَالَّذِينَ يُؤْمِنُونَ بِمَا أُنزِلَ إِلَيْكَ وَمَا أُنزِلَ مِن قَبْلِكَ وَبِالْآخِرَةِ هُمْ يُوقِنُونَ','qui croient à ce qui t’a été descendu et à ce qui a été descendu avant toi, et qui croient fermement à la vie future.','who believe in what has been revealed to you and what was revealed before you, and have sure faith in the Hereafter.']
];
const state={lang:'fr',verse:1,playing:false,ayahs:[],tafsirLoaded:false};
const $=s=>document.querySelector(s);const ui={ar:$('#arabicText'),tr:$('#translationText'),num:$('#verseNumber'),select:$('#verseSelect'),progress:$('#progressBar'),progressText:$('#progressText'),attr:$('#translationAttribution'),audio:$('#recitation'),audioState:$('#audioState'),audioTitle:$('#audioTitle'),play:$('#audioToggle'),tafsir:$('#tafsirText'),tafsirRef:$('#tafsirRef'),label:$('#readingLabel')};
const labels={fr:{read:'Lecture en français',attr:'Traduction française — Hamidullah',ready:'Prêt à écouter',playing:'Lecture en cours · appuyez pour pause',pause:'❚❚'},en:{read:'Reading in English',attr:'English translation — Saheeh International',ready:'Ready to listen',playing:'Playing · press to pause',pause:'❚❚'},ar:{read:'القراءة بالعربية',attr:'النص العربي',ready:'جاهز للاستماع',playing:'جاري التلاوة · اضغط للإيقاف',pause:'❚❚'}};
function audioUrl(n){return `https://everyayah.com/data/Abdurrahmaan_As-Sudais_192kbps/002${String(n).padStart(3,'0')}.mp3`}
function verseData(n){return state.ayahs[n-1]||{ar:fallback[n-1]?.[0]||'Le contenu de cette ayah est en cours de chargement.',fr:fallback[n-1]?.[1]||'Chargement de la traduction…',en:fallback[n-1]?.[2]||'Loading translation…'}}
function render(){const v=verseData(state.verse),l=labels[state.lang];document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr';ui.ar.textContent=v.ar;ui.tr.textContent=state.lang==='ar'?v.ar:v[state.lang];ui.num.textContent=state.lang==='ar'?`الآية ${state.verse}`:`AYAH ${state.verse}`;ui.attr.textContent=l.attr;ui.progress.style.width=`${state.verse/286*100}%`;ui.progressText.textContent=`${state.verse} / 286`;ui.select.value=state.verse;ui.audioTitle.textContent=`Ayah ${state.verse}`;ui.tafsirRef.textContent=`Al‑Baqarah · ${state.verse}`;ui.label.textContent=l.read;ui.tafsir.innerHTML='<p>Chargement du tafsir d’Ibn Kathîr…</p>';if(state.playing){ui.audio.src=audioUrl(state.verse);ui.audio.play().catch(()=>stopAudio())}tafsir()}
function change(n){state.verse=Math.max(1,Math.min(286,n));render()}
function stopAudio(){state.playing=false;ui.audio.pause();ui.play.textContent='▶';ui.audioState.textContent=labels[state.lang].ready}
function toggleAudio(){if(state.playing){stopAudio();return}state.playing=true;ui.audio.src=audioUrl(state.verse);ui.audio.play().then(()=>{ui.play.textContent=labels[state.lang].pause;ui.audioState.textContent=labels[state.lang].playing}).catch(()=>{stopAudio();ui.audioState.textContent='Audio indisponible. Vérifiez votre connexion.'})}
function normalize(data){const verses=data.verses||data.chapter?.verses||data.data?.verses||[];return verses.map(v=>({ar:v.text||v.text_uthmani||v.arabic||'',fr:v.translation||v.translations?.[0]?.text||'',en:v.translation||v.translations?.[0]?.text||''}))}
async function loadAll(){try{const base='https://cdn.jsdelivr.net/npm/quran-json@3.1.2/dist/chapters/';const [ar,fr,en]=await Promise.all([fetch(base+'2.json'),fetch(base+'fr/2.json'),fetch(base+'en/2.json')].map(r=>r.then(x=>x.json())));const A=normalize(ar),F=normalize(fr),E=normalize(en);if(A.length<286)throw Error('missing verses');state.ayahs=A.map((x,i)=>({ar:x.ar,fr:F[i]?.fr||F[i]?.ar,en:E[i]?.en||E[i]?.ar}));render()}catch(e){ui.audioState.textContent='Mode hors ligne : les premières ayah restent disponibles.'}}
function structuredTafsir(text){const sentences=text.replace(/\s+/g,' ').trim().match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[text];const groups=[];for(let i=0;i<sentences.length;i+=3)groups.push(sentences.slice(i,i+3).join(' ').trim());return `<article class="tafsir-reading"><span class="reading-kicker">ÉCLAIRAGE DU VERSET</span>${groups.filter(Boolean).map((paragraph,i)=>`<p class="${i===0?'lead':''}">${paragraph}</p>`).join('')}</article>`}
async function tafsir(){const requestedVerse=state.verse;const requestedLanguage=state.lang;ui.tafsir.innerHTML='<p>Chargement du tafsir d’Ibn Kathîr…</p>';try{const resource=requestedLanguage==='ar'?14:169;const r=await fetch(`https://api.quran.com/api/v4/tafsirs/${resource}/by_ayah/2:${requestedVerse}`);const d=await r.json(),text=d.tafsir?.text||d.tafsir?.[0]?.text;if(!text)throw Error();if(requestedLanguage==='fr'){const plain=text.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();const t=await fetch(`https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=fr&dt=t&q=${encodeURIComponent(plain.slice(0,4500))}`).then(x=>x.json());if(requestedVerse!==state.verse||requestedLanguage!==state.lang)return;ui.tafsir.innerHTML=`${structuredTafsir(t[0].map(x=>x[0]).join(''))}<small class="translation-note">Adaptation française du tafsir anglais d’Ibn Kathîr.</small>`}else{if(requestedVerse!==state.verse||requestedLanguage!==state.lang)return;ui.tafsir.innerHTML=`<article class="tafsir-reading ${requestedLanguage==='ar'?'arabic':''}"><span class="reading-kicker">${requestedLanguage==='ar'?'تفسير الآية':'VERSE EXPLAINED'}</span>${text}</article>`}}catch(e){if(requestedVerse===state.verse&&requestedLanguage===state.lang)ui.tafsir.innerHTML='<p>Le tafsir n’a pas pu être chargé maintenant. Réessayez avec le bouton ci-dessus.</p>'}}
for(let i=1;i<=286;i++){const o=document.createElement('option');o.value=i;o.textContent=`Ayah ${i}`;ui.select.append(o)}
$('#language').onchange=e=>{state.lang=e.target.value;stopAudio();render()};ui.select.onchange=e=>change(+e.target.value);$('#previousVerse').onclick=()=>change(state.verse-1);$('#nextVerse').onclick=()=>change(state.verse+1);ui.play.onclick=toggleAudio;$('#loadTafsir').onclick=tafsir;$('#tafsirSize').onclick=e=>{const large=$('.tafsir-box').classList.toggle('large-type');e.currentTarget.textContent=large?'A−':'A+'};ui.audio.onended=()=>state.verse<286?(state.verse++,render()):stopAudio();document.querySelectorAll('[data-theme]').forEach(button=>button.onclick=()=>{document.body.dataset.theme=button.dataset.theme==='white'?'':button.dataset.theme;document.querySelectorAll('[data-theme]').forEach(x=>x.classList.toggle('active',x===button))});$('#reflectionButton').onclick=()=>{stopAudio();const prompts=['Quelle parole de cette ayah veux-tu garder avec toi aujourd’hui ?','Quel mot as-tu besoin de relire plus lentement ?','Comment cette ayah peut-elle guider une petite action aujourd’hui ?','Lis encore une fois. Qu’est-ce qui est devenu plus clair ?'];$('#reflectionText').textContent=prompts[(state.verse-1)%prompts.length];$('#reflectionButton').textContent='Revenir à la récitation'};render();loadAll();
